# frontend/nginx.conf

# Configuração de Rate Limit: Permite 5 requisições por segundo por IP
limit_req_zone $binary_remote_addr zone=api_limit:10m rate=5r/s;

server {
    listen 80;
    server_name localhost;

    # Security Headers (OWASP)
    add_header X-Frame-Options "DENY" always; # Previne Clickjacking (que seu site seja embutido em iframes falsos)
    add_header X-Content-Type-Options "nosniff" always; # Previne MIME-sniffing
    add_header X-XSS-Protection "1; mode=block" always; # Bloqueia cross-site scripting basico
    
    # Esconde a versão do Nginx e do sistema operacional
    server_tokens off;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        # Aplica o Rate Limit configurado acima (se passar da taxa, dá erro 503)
        limit_req zone=api_limit burst=10 nodelay;

        proxy_pass http://backend:8000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    
    # Reverse proxy for FastAPI developer endpoints
    location = /docs {
         # Aplica o Rate Limit configurado acima (se passar da taxa, dá erro 503)
        limit_req zone=api_limit burst=10 nodelay;

        proxy_pass http://backend:8000/docs;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location = /redoc {
         # Aplica o Rate Limit configurado acima (se passar da taxa, dá erro 503)
        limit_req zone=api_limit burst=10 nodelay;

        proxy_pass http://backend:8000/redoc;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
    location = /openapi.json {
         # Aplica o Rate Limit configurado acima (se passar da taxa, dá erro 503)
        limit_req zone=api_limit burst=10 nodelay;
        
        proxy_pass http://backend:8000/openapi.json;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}