# docker-compose.yml
services:
  db:
    image: postgres:15-alpine
    container_name: painel_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      # Explicitly bind to 127.0.0.1 to prevent external internet access to the DB port
      - "127.0.0.1:${DATABASE_SECRET_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: painel_backend
    restart: always
    depends_on:
      - db
    ports:
      - "${BACKEND_SECRET_PORT}:8000"
    volumes:
      - ./backend:/app
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - PDF_ENGINE=${PDF_ENGINE}
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    build:
      context: ./frontend
    container_name: painel_frontend
    restart: always
    depends_on:
      - backend
    environment:
      - FRONTEND_SECRET_PORT=${FRONTEND_SECRET_PORT}
    volumes:
      - ./frontend/:/usr/share/nginx/html/
    ports:
      - "${FRONTEND_SECRET_PORT}:80"

volumes:
  postgres_data: