# backend/src/core/constants.py
from enum import Enum

class PdfEngineType(str, Enum):
    PLAYWRIGHT = "playwright"
    # WEASYPRINT = "weasyprint"
    # WKHTMLTOPDF = "wkhtmltopdf"
    # PUPPETEER = "puppeteer"
    
class ErrorKeys(str, Enum):
    DB_CONNECTION_FAILED = "ERR_DB_CONNECTION_FAILED"
    COUNTY_STATISTICS_NOT_FOUND = "ERR_COUNTY_STATISTICS_NOT_FOUND"
    COUNTY_NOT_FOUND = "ERR_COUNTY_NOT_FOUND"
    RISK_FACTOR_NOT_FOUND = "ERR_RISK_FACTOR_NOT_FOUND"
    DATA_RETRIEVAL_FAILED = "ERR_DATA_RETRIEVAL_FAILED"
    PDF_GENERATION_FAILED = "ERR_PDF_GENERATION_FAILED"
    ADAPTA_RISKS_NOT_FOUND = "ERR_ADAPTA_RISKS_NOT_FOUND"
    ADAPTA_MAIN_FACTORS_NOT_FOUND = "ERR_ADAPTA_MAIN_FACTORS_NOT_FOUND"
    INVALID_PDF_ENGINE = "ERR_INVALID_PDF_ENGINE"