# backend/src/core/constants.py
from enum import Enum

class PdfEngineType(str, Enum):
    PLAYWRIGHT = "playwright"
    # WEASYPRINT = "weasyprint"
    # WKHTMLTOPDF = "wkhtmltopdf"
    # PUPPETEER = "puppeteer"
    
class ErrorKeys(str, Enum):
    # General Errors
    DB_CONNECTION_FAILED = "ERR_DB_CONNECTION_FAILED"
    DATA_RETRIEVAL_FAILED = "ERR_DATA_RETRIEVAL_FAILED"
    PDF_GENERATION_FAILED = "ERR_PDF_GENERATION_FAILED"
    INVALID_PDF_ENGINE = "ERR_INVALID_PDF_ENGINE"

    # Table Errors
    COUNTY_NOT_FOUND = "ERR_COUNTY_NOT_FOUND"
    RISK_FACTOR_NOT_FOUND = "ERR_RISK_FACTOR_NOT_FOUND"
    MUNICIPAL_REPORT_NOT_FOUND = "ERR_MUNICIPAL_REPORT_NOT_FOUND"
    MUNICIPAL_RESILIENCE_PROFILE_NOT_FOUND = "ERR_MUNICIPAL_RESILIENCE_PROFILE_NOT_FOUND"
    